server:
  port: 10001
kaptcha:
  height: 50
  width: 200
  content:
    length: 4
    source: abcdefghjklmnopqrstuvwxyz23456789
    space: 2
  font:
    color: black
    name: Arial
    size: 40
  background-color:
    from: lightGray
    to: white
  border:
    enabled: true
    color: black
    thickness: 1
baidu:
  translate:
    appid: 20221008001377417
    securityKey: XuG2V_1pfJ_JaO9NlW8n
